/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.EnterpriseAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.Broker;
import static Business.Enterprise.Enterprise.EnterpriseType.Investor;
import static Business.Enterprise.Enterprise.EnterpriseType.Miner;
import Business.Organizaiton.Organization;
import Business.Organizaiton.Organization.Type;
import static Business.Organizaiton.Organization.Type.Cashier;
import Business.Organizaiton.OrganizationDirectory;
import Business.Role.MinerRole;
import Business.Role.Role;
import static Business.Role.Role.RoleType.trader;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author raywa
 */
public class manageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form manageOrganizationJPanel
     */
    private JPanel processPanel;
    private OrganizationDirectory directory;
    private Enterprise enterprise;
    public manageOrganizationJPanel(JPanel processPanel, OrganizationDirectory directory, Enterprise enterprise) {
        initComponents();
        this.processPanel = processPanel;
        this.directory = directory;
        this.enterprise = enterprise;
        refreshTbl();
        populateComboboxOrganization();
    }
    public void refreshTbl(){
        int rowCount = TblOrganization.getRowCount();
        DefaultTableModel model = (DefaultTableModel) TblOrganization.getModel();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for(Organization o: directory.getOrganizationList()){
                Object row[] = new Object[2];
                row[0] = o.getName();
                model.addRow(row);
        }
    }
    private void populateComboboxOrganization(){
        CmbEnterpriseType.removeAllItems();
        for (Type type : Organization.Type.values()){
            if (!type.getValue().equals(Type.EnterpriseAdmin.getValue()))
                CmbEnterpriseType.addItem(type);
        }
        /*
        for (Role r: enterprise.getSupportedRole()){
            if (r.equals(Miner) && enterprise.getEnterpriseType().equals(Miner)){
                CmbEnterpriseType.addItem(Miner);
            }else if (r.equals(trader) && enterprise.getEnterpriseType().equals(Investor)){
                CmbEnterpriseType.addItem(Investor);
            }else if (r.equals(Cashier) && enterprise.getEnterpriseType().equals(Broker)){
                CmbEnterpriseType.addItem(Broker);
            } 
        }
        */
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblOrganization = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        BtnSubmit = new javax.swing.JButton();
        CmbEnterpriseType = new javax.swing.JComboBox();

        TblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Name"
            }
        ));
        jScrollPane1.setViewportView(TblOrganization);
        if (TblOrganization.getColumnModel().getColumnCount() > 0) {
            TblOrganization.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel1.setText("Organization Type: ");

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        BtnSubmit.setText("Submit");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });

        CmbEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(BtnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSubmit)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBack)
                    .addComponent(BtnSubmit))
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
         processPanel.remove(this);
        Component[] componentArray = processPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EnterpriseAdminWorkAreaJPanel enterpriseAdmin = (EnterpriseAdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) processPanel.getLayout();
        layout.previous(processPanel);
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
        // TODO add your handling code here:
        Type t = (Type)CmbEnterpriseType.getSelectedItem();
        directory.createOrganization(t);
        refreshTbl();
    }//GEN-LAST:event_BtnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JComboBox CmbEnterpriseType;
    private javax.swing.JTable TblOrganization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
