/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.TraderRole;

import Blockchain.Transaction;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InvestorEnterprise;
import Business.Network.Network;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.MinerRole.MinerWorkAreaJPanel;

/**
 *
 * @author Administrator
 */
public class RequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HistoryJPanel
     */
    private JPanel processPanel;
    private EcoSystem business;
    private Enterprise e;

    public RequestJPanel(JPanel processPanel, EcoSystem business, Enterprise e) {
        initComponents();
        this.processPanel = processPanel;
        this.business = business;
        this.e = e;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtTotalCoins = new javax.swing.JTextField();
        txtReceiveId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnRequest = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Request");

        jLabel1.setText("Total Coins:");

        jLabel3.setText("Send Organization ID:");

        BtnRequest.setText("Request");
        BtnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRequestActionPerformed(evt);
            }
        });

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotalCoins, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(txtReceiveId)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(BtnRequest)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBack)))
                .addContainerGap(638, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtReceiveId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRequest)
                    .addComponent(BtnBack))
                .addContainerGap(331, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        processPanel.remove(this);
        Component[] componentArray = processPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TraderWorkAreaJPanel traderArea = (TraderWorkAreaJPanel) component;
        traderArea.populateTbl();
        CardLayout layout = (CardLayout) processPanel.getLayout();
        layout.previous(processPanel);
        
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRequestActionPerformed
         
        if (txtTotalCoins.getText().equals(" ") || txtReceiveId.getText().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Please fill the blank");
        } else {
            Pattern intPattern = Pattern.compile("^\\d+$");
            if(intPattern.matcher(txtTotalCoins.getText()).matches() &&intPattern.matcher(txtReceiveId.getText()).matches()){
            if (Float.parseFloat(txtTotalCoins.getText()) <= 0) {
                JOptionPane.showMessageDialog(null, "Invalid coin amount entered");
            }
            else if(Integer.parseInt(txtReceiveId.getText())==e.getenterpriseId()){
                         JOptionPane.showMessageDialog(null, "You need to request from others");
            }
            else {
                int a = 0;
                for (Network n : business.getNetworkList()) {
                    for (int i = 0; i < n.getEnterpriseDirectory().getEnterpriseList().size(); i++) {

                        if (Integer.parseInt(txtReceiveId.getText()) == n.getEnterpriseDirectory().getEnterpriseList().get(i).getenterpriseId()) {
                            a = 1;
                            WorkRequest w = new WorkRequest();
                            Transaction t = new Transaction();
                            t.setBtcAmount(Integer.parseInt(txtTotalCoins.getText()));
                            t.setFrom(n.getEnterpriseDirectory().getEnterpriseList().get(i).getenterpriseId());
                          
                            t.setLocktime(" ");
                            t.setTo(e.getenterpriseId());
                            t.refreshTranHashcode();
                            t.setTransactionDate(new Date());
                            w.setStatus("Coin Requested");
                            w.setT(t);
                            business.getWorkQueue().getWorkRequestList().add(w);
                            JOptionPane.showMessageDialog(null, "Request submitted");
                            txtReceiveId.setText(" ");
                            txtTotalCoins.setText(" ");
                            break;
                        }
                    }
                }
            }
        }}       // TODO add your handling code here:
    }//GEN-LAST:event_BtnRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtReceiveId;
    private javax.swing.JTextField txtTotalCoins;
    // End of variables declaration//GEN-END:variables
}
